"""add_concession_fields_to_activities

Revision ID: 8784a14e4bcf
Revises: 285798fb4d19
Create Date: 2026-08-12 15:32:31.050908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8784a14e4bcf'
down_revision: Union[str, Sequence[str], None] = '285798fb4d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('group_item', sa.String(length=255), nullable=True))
    op.add_column('activities', sa.Column('contract', sa.String(length=255), nullable=True))
    op.add_column('activities', sa.Column('step_number', sa.String(length=50), nullable=True))
    op.add_column('activities', sa.Column('actual_start_date', sa.Date(), nullable=True))
    op.add_column('activities', sa.Column('delay_justification_problem', sa.Text(), nullable=True))
    op.add_column('activities', sa.Column('delay_justification_action', sa.Text(), nullable=True))
    op.add_column('activities', sa.Column('delay_justification_responsible', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'delay_justification_responsible')
    op.drop_column('activities', 'delay_justification_action')
    op.drop_column('activities', 'delay_justification_problem')
    op.drop_column('activities', 'actual_start_date')
    op.drop_column('activities', 'step_number')
    op.drop_column('activities', 'contract')
    op.drop_column('activities', 'group_item')
    # ### end Alembic commands ###
